services:
  app:
    build: .
    profiles:
      - app
    stdin_open: true
    tty: true
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: medix
      PGUSER: medix
      PGPASSWORD: medix
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: medix
      POSTGRES_USER: medix
      POSTGRES_PASSWORD: medix
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
