-- WARNING: DO NOT EDIT THIS FILE; IT IS GENERATED AUTOMATICALLY BY THE MIGRATION GENERATOR
-- EDITING IT WILL CAUSE UNEXPECTED BEHAVIOUR

local Model = require("orm.model")
local Types = require("orm.model.types")
local Constraint = require("orm.model.constraint")
local CurrentTimestamp = require("orm.model.expressions.current-timestamp")

return {
	["specializations"] = Model("specializations", {
		{ "id", Types.Int, Constraint.PrimaryKey, Constraint.AutoIncrement(Constraint.IdentityMode.BY_DEFAULT), Constraint.NotNull },
		{ "name", Types.Text, Constraint.NotNull }
	}),

	["doctors"] = Model("doctors", {
		{ "id", Types.Int, Constraint.PrimaryKey, Constraint.AutoIncrement(Constraint.IdentityMode.BY_DEFAULT), Constraint.NotNull },
		{ "firstName", Types.Text, Constraint.NotNull },
		{ "lastName", Types.Text, Constraint.NotNull },
		{ "specialization_id", Types.Int, Constraint.ForeignKey("specializations", "id"), Constraint.NotNull }
	}),

	["appointments"] = Model("appointments", {
		{ "id", Types.Int, Constraint.PrimaryKey, Constraint.AutoIncrement(Constraint.IdentityMode.ALWAYS), Constraint.NotNull },
		{ "scheduledAt", Types.TimestampTz, Constraint.NotNull },
		{ "patient_id", Types.Int, Constraint.ForeignKey("patients", "id"), Constraint.NotNull },
		{ "specialist_id", Types.Int, Constraint.ForeignKey("doctors", "id"), Constraint.NotNull },
		{ "procedure_id", Types.Int, Constraint.ForeignKey("procedures", "id"), Constraint.NotNull }
	}),

	["patientHistoriesMedications"] = Model("patientHistoriesMedications", {
		{ "id", Types.Int, Constraint.PrimaryKey, Constraint.AutoIncrement(Constraint.IdentityMode.ALWAYS), Constraint.NotNull },
		{ "patientHistory_id", Types.Int, Constraint.ForeignKey("patientHistories", "id"), Constraint.NotNull },
		{ "medication_id", Types.Int, Constraint.ForeignKey("medications", "id"), Constraint.NotNull }
	}),

	["medications"] = Model("medications", {
		{ "id", Types.Int, Constraint.PrimaryKey, Constraint.AutoIncrement(Constraint.IdentityMode.ALWAYS), Constraint.NotNull },
		{ "name", Types.Text, Constraint.Unique, Constraint.NotNull },
		{ "dosage", Types.Text, Constraint.NotNull },
		{ "frequency", Types.Text, Constraint.NotNull }
	}),

	["patientHistories"] = Model("patientHistories", {
		{ "id", Types.Int, Constraint.PrimaryKey, Constraint.AutoIncrement(Constraint.IdentityMode.ALWAYS), Constraint.NotNull },
		{ "diagnosis", Types.Text },
		{ "fromDate", Types.Timestamp, Constraint.NotNull },
		{ "toDate", Types.Timestamp },
		{ "doctor_id", Types.Int, Constraint.ForeignKey("doctors", "id"), Constraint.NotNull },
		{ "patient_id", Types.Int, Constraint.ForeignKey("patients", "id"), Constraint.NotNull }
	}),

	["patients"] = Model("patients", {
		{ "id", Types.Int, Constraint.PrimaryKey, Constraint.AutoIncrement(Constraint.IdentityMode.ALWAYS), Constraint.NotNull },
		{ "firstName", Types.Text, Constraint.NotNull },
		{ "lastName", Types.Text, Constraint.NotNull },
		{ "oib", Types.Char(11), Constraint.Unique, Constraint.NotNull },
		{ "dateOfBirth", Types.Timestamp, Constraint.NotNull },
		{ "sex", Types.Char(), Constraint.NotNull },
		{ "permamentAddress", Types.Text, Constraint.NotNull },
		{ "secondaryAddress", Types.Text, Constraint.NotNull }
	}),

	["procedures"] = Model("procedures", {
		{ "id", Types.Int, Constraint.PrimaryKey, Constraint.AutoIncrement(Constraint.IdentityMode.ALWAYS), Constraint.NotNull },
		{ "name", Types.Text, Constraint.Unique, Constraint.NotNull }
	})
}
